branches:
  except: # Version Tags
    - /^\d+\.\d+\.\d+(\-\S*)?(\+\S*)?$/

matrix:
  include:
    - &macos
      name: "Check if it compiles and runs on macOS"
      os: osx
      osx_image: xcode10.3
      sudo: required
      language: objective-c
      script: &tests
        - swift package update
        - swift build

    - &linux
      name: "Check if it compiles and runs on Linux"
      os: linux
      dist: bionic
      sudo: required
      before_install:
        - sudo apt-get install clang libicu-dev libssl1.0-dev
        - mkdir swift
        - export SWIFT_ARCHIVE_URL="https://swift.org/builds/swift-4.2.4-release/ubuntu1804/swift-4.2.4-RELEASE/swift-4.2.4-RELEASE-ubuntu18.04.tar.gz"
        - curl ${SWIFT_ARCHIVE_URL} -o ../swift.tar.gz
        - mkdir ../swift
        - tar xzf ../swift.tar.gz -C ../swift --strip-components 2
        - export PATH="$(dirname $(pwd))/swift/bin:$PATH"
      script: *tests
      
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
